make e2e framework as a separate module
vmware-tanzu/tanzu-cli pull request #221
Opened 2023-04-18 16:49 UTC by chandrareddyp

### What this PR does / why we need it

### Which issue(s) this PR fixes

Fixes #

### Describe testing done for PR

### Release note

```release-note

```

### Additional information

#### Special notes for your reviewer

2023-04-24 15:11 UTC, mpanchajanya commented on test/e2e/go.mod
> +	github.com/onsi/ginkgo v1.16.5
@chandrareddyp ginkgo version is upgraded to  v2   in main. pls rebase and use ginkgo v2 here

2023-04-24 15:12 UTC, mpanchajanya requested changes
LGTM! update ginkgo to use v2

2023-04-25 19:50 UTC, mpanchajanya approved these changes
LGTM

2023-04-25 19:52 UTC, anujc25 approved these changes
LGTM.

2023-04-25 20:03 UTC, merged